language: python

python:
  - "3.6"

services:
  - xvfb

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y scilab
  - "export DISPLAY=:99.0"
  - sleep 3 # give xvfb some time to start

# command to install dependencies
install:
  - pip install -r requirements/requirements-common.txt
  - pip install codecov
  - python setup.py develop

# command to run tests and coverage
script:
  - python manage.py makemigrations
  - python manage.py migrate
  - coverage erase
  - coverage run -p manage.py test -v 2 --settings online_test.test_settings yaksh
  - coverage run -p manage.py test -v 2 --settings online_test.test_settings grades
  - coverage run -p manage.py test -v 2 --settings online_test.test_settings yaksh.live_server_tests.load_test

after_success:
  - coverage combine
  - coverage report
  - codecov

sudo:
    required

dist:
    xenial

addons:
  firefox: "46.0"
